[env:lilygo_tdeck_plus]
platform = espressif32
board = esp32s3box
framework = arduino
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

lib_deps =
    bblanchon/ArduinoJson@^7
    lovyan03/LovyanGFX@^1

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -std=gnu++17

monitor_speed = 115200
